services:
  bitwise:
    container_name: bitwise
    build:
      context: .
    image: untilov/bitwise
    ports:
      - 3000:3000
    # restart: always
  nginx:
    container_name: nginx
    build:
      context: nginx
    image: untilov/nginx
    ports:
      - "8080:80"
      - "4430:443"
    # restart: always
